Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
    end

=begin
    Using puppet

    config.vm.define "mysqldb" do |mysqldb|
      mysqldb.vm.network "public_network", ip: "192.168.1.24"

      mysqldb.vm.provision "shell", path: "script.sh"

      mysqldb.vm.synced_folder "./config/", "/config"
      mysqldb.vm.synced_folder ".", "/vagrant", disabled: true
    end
=end 

    config.vm.define "phpweb" do |phpweb|
      phpweb.vm.network "forwarded_port", guest: 8888, host:8888
      phpweb.vm.network "public_network", ip: "192.168.0.223", bridge: "enp4s0"

      phpweb.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 2
        vb.name = "ubuntu_bionic_php7"
      end

      phpweb.vm.provision "shell", 
        inline: "apt-get update && apt-get install -y puppet"        

      phpweb.vm.provision "puppet" do |puppet|
        puppet.manifests_path = "./config/manifests"
        puppet.manifest_file = "phpweb.pp"
      end

    end


    config.vm.define "mysqlserver" do |mysqlserver|
      
      mysqlserver.vm.network "public_network", ip: "192.168.0.222", bridge: "enp4s0"
      mysqlserver.vm.synced_folder "./config/", "/config"
      
      mysqlserver.vm.provision "shell",
            inline: "cat /vagrant/config/id_bionic.pub >> .ssh/authorized_keys"
      
      mysqlserver.vm.provision "shell",
            inline: "cp /vagrant/config/mysqld.cnf mysqld.cnf"

      mysqlserver.vm.provision "ansible" do |ansible|
        ansible.playbook = "./config/ansible/playbook.yml"
        ansible.inventory_path = "./config/ansible/hosts" 
      end

    end
    

=begin

    If using ansible also in a VM.

    config.vm.define "ansible" do |ansible|
      ansible.vm.network "public_network", ip: "192.168.1.26"
  
      ansible.vm.provision "shell",
            inline: "cp /vagrant/indbionic /home/vagrant && \
                     chmod 600 /home/vagrant/id_bionic && \
                     chown vagrant:vagrant /home/vagrant/id_bionic"
=end

  end