server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        #git:
        #  uri:
        #  search-paths:
        native:
          search-locations: E:/Programacao/Java/SpringCourses/Alura_SpringBootMicroservices/microservice-repo
