server:
  port: 8761
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    fetch-registry: false
    register-with:eureka: false
  server:
    enable-self-preservation: true
    wait-time-in-ms-when-sync-empty: 0
